output "resource_group" {
  value = azurerm_resource_group.lab.name
}

output "log_analytics_workspace_name" {
  value = azurerm_log_analytics_workspace.lab.name
}

output "log_analytics_workspace_customer_id" {
  description = "Workspace GUID used by `az monitor log-analytics query -w`."
  value       = azurerm_log_analytics_workspace.lab.workspace_id
}

output "sentinel_portal_url" {
  value = "https://portal.azure.com/#view/Microsoft_Azure_Security_Insights/MainMenuBlade/~/0/id/${urlencode(azurerm_log_analytics_workspace.lab.id)}"
}

output "deployed_detections" {
  description = "Detection IDs deployed as Sentinel analytics rules."
  value       = sort(keys(local.detections))
}

output "skipped_detections" {
  description = "Detections not deployed (disabled, or a required data source is switched off)."
  value       = sort([for f, d in local.detection_raw : d.id if !contains(keys(local.detections), d.id)])
}

output "key_vault_name" {
  value = azurerm_key_vault.canary.name
}

output "storage_account_name" {
  value = azurerm_storage_account.canary.name
}

output "linux_admin_private_key" {
  description = "Only needed if you add a Bastion host. `terraform output -raw linux_admin_private_key`."
  value       = tls_private_key.linux_admin.private_key_openssh
  sensitive   = true
}

# Hand the simulation scripts everything they need. No secrets in here.
resource "local_file" "sim_env" {
  filename        = "${path.module}/../simulate/lab.env"
  file_permission = "0600"
  content         = <<-ENV
    # Generated by Terraform - do not edit, do not commit.
    SUBSCRIPTION_ID="${data.azurerm_subscription.current.subscription_id}"
    RG="${azurerm_resource_group.lab.name}"
    LAW_NAME="${azurerm_log_analytics_workspace.lab.name}"
    LAW_ID="${azurerm_log_analytics_workspace.lab.id}"
    LAW_CUSTOMER_ID="${azurerm_log_analytics_workspace.lab.workspace_id}"
    KV_NAME="${azurerm_key_vault.canary.name}"
    CANARY_SECRET="${local.canary_secret_name}"
    DECOY_SECRETS="${join(" ", local.decoy_secret_names)}"
    STORAGE_ACCOUNT="${azurerm_storage_account.canary.name}"
    CANARY_CONTAINER="${azurerm_storage_container.canary.name}"
    CANARY_BLOB="${local.canary_blob_name}"
    SIM_NSG="${azurerm_network_security_group.sim.name}"
    SIM_NSG_ID="${azurerm_network_security_group.sim.id}"
    SIM_IDENTITY_PRINCIPAL_ID="${azurerm_user_assigned_identity.sim_target.principal_id}"
    WIN_VM="${var.deploy_windows_vm ? azurerm_windows_virtual_machine.win[0].name : ""}"
    LINUX_VM="${var.deploy_linux_vm ? azurerm_linux_virtual_machine.linux[0].name : ""}"
  ENV
}
