#!/usr/bin/env bash
# ENT-007: Identity Protection risk cannot be faked through an API - it is
# Microsoft's own detection. This prints the documented manual procedure.
# shellcheck source=../lib/common.sh
source "$(dirname "$0")/../lib/common.sh"
require_env
require_entra
[[ "${ENTRA_P2:-false}" == "true" ]] || { warn "entra_id_p2 = false - skipping"; exit 0; }
banner "Identity Protection risk (manual)" "ENT-007"
record_run "ent-007-identity-protection-risk"

cat <<'TXT'
Identity Protection risk detections are generated by Microsoft, so this
scenario is manual. Use a dedicated, ENABLED test user (not a canary
account, and never a real person's account):

  Anonymous IP address (medium risk, appears within ~10-15 min):
    1. Install Tor Browser.
    2. Browse to https://myapps.microsoft.com and sign in as the test user.

  Unfamiliar sign-in properties:
    Sign in from a new browser + VPN location after the account has a
    sign-in history from your normal location.

Microsoft's guide:
  https://learn.microsoft.com/entra/id-protection/howto-identity-protection-simulate-risk

Then check Entra admin center > Protection > Identity Protection > Risky sign-ins,
and run ./simulate/verify.sh 2
TXT
